### ISSUE TITLE
Questions about dividing data into chunks

### ISSUE THREAD

**Issue by abgnwl** [smuellerDD/libkcapi#139]
Hello, I am reading the source code of libkcapi. I have some questions on `_kcapi_cipher_crypt_chunk`. 

I see that `impl_cipher_encrypt`(in `kcapi-sym.c`) processes pagesize*ALG_MAX_PAGES (=65536 on my computer) bytes of data each time, but `impl_aead_encrypt` in `kcapi-aead.c` directly call `_kcapi_cipher_crypt`.

My questions:
1. Why does `impl_cipher_encrypt` divide data into chunks, but `impl_aead_encrypt` does not?
2. Does ALG kernel process pagesize*ALG_MAX_PAGES bytes each time?
3. assuming using `KCAPI_ACCESS_SENDMSG`, what happens if I send larger data (> pagesize*ALG_MAX_PAGES) to the kernel in  `_kcapi_cipher_crypt`?

Thanks

**Comment by smuellerDD** [comment]
Am Montag, 23. Mai 2022, 17:13:00 CEST schrieb Lizijue:

Hi Lizijue,

> Hello, I am reading the source code of libkcapi. I have some questions on
> `_kcapi_cipher_crypt_chunk`.
> 
> I see that `impl_cipher_encrypt`(in `kcapi-sym.c`) processes
> pagesize*ALG_MAX_PAGES (=65536 on my computer) bytes of data each time, but
> `impl_aead_encrypt` in `kcapi-aead.c` directly call `_kcapi_cipher_crypt`.
> 
> My questions:
> 1. Why does `impl_cipher_encrypt` divide data into chunks, but
> `impl_aead_encrypt` does not?

Symmetric ciphers allow multiple invocations - see the stream API. AEAD does 
not allow this. I.e. you have one-shot calls only due to the tag calculation.

> 2. Does ALG kernel process
> pagesize*ALG_MAX_PAGES bytes each time?

Not sure what you mean, but it processes up to to this amount of memory for 
one call.

> 3. assuming using
> `KCAPI_ACCESS_SENDMSG`, what happens if I send larger data (>
> pagesize*ALG_MAX_PAGES) to the kernel in  `_kcapi_cipher_crypt`?

The kernel could stall your call because it waits for more input data before 
processing the data. But user space cannot send it.

> 
> Thanks


Ciao
Stephan

**Comment by abgnwl** [comment]
Thank you for your answer. I still have some questions:
1. I saw a NOTE: `The kernel will only process sysconf(_SC_PAGESIZE) * ALG_MAX_PAGES at one time`. I try to use `kcapi_aead_encrypt` with `gcm(aes)` algorithm, sendmsg 200KB data. The encryption is successful. Using AF_ALG interface directly and sendmsg 200KB is also successful. It looks like kernel crypto doesn't have the limit of `sysconf(_SC_PAGESIZE) * ALG_MAX_PAGES`. Am I misunderstanding this note?
2. In `KCAPI_ACCESS_SENDMSG` scenario, what's the benefit of dividing data into chunks than sending all data one-shot in function `_kcapi_cipher_crypt_chunk`?

**Comment by smuellerDD** [comment]
Am Dienstag, 24. Mai 2022, 08:04:55 CEST schrieb Lizijue:

Hi Lizijue,

sorry for the delay, but other development work kept me busy.

> Thank you for your answer. I still have some questions:
> 1. I saw a NOTE: `The kernel will only process sysconf(_SC_PAGESIZE) *
> ALG_MAX_PAGES at one time`. I try to use `kcapi_aead_encrypt` with
> `gcm(aes)` algorithm, sendmsg 200KB data. The encryption is successful.
> Using AF_ALG interface directly and sendmsg 200KB is also successful. It
> looks like kernel crypto doesn't have the limit of `sysconf(_SC_PAGESIZE) *
> ALG_MAX_PAGES`. Am I misunderstanding this note?

I see your point. The limitation applies to the vmsplice call. Using sendmsg, 
the limit would be defined by the per-socket wait queue length. Check what 
value you have in /proc/sys/net/core/optmem_max.

You could even increase the vmsplice call supported size by using 
kcapi_set_maxsplicesize. 

Maybe I should update the guidance to be a bit more clear here as I forgot to 
update it after adding kcapi_set_maxsplicesize and considering the 
aforementioned proc file.

> 2. In
> `KCAPI_ACCESS_SENDMSG` scenario, what's the benefit of dividing data into
> chunks than sending all data one-shot in function
> `_kcapi_cipher_crypt_chunk`?

The issue is that at the kernel has to reserve memory. And it will only do 
that to a certain amount. If you try to pump in more, the kernel will return 
with an error.

For sendmsg, the kernel will use the per-socket memory. For vmsplice the pipe 
size value is used to limit the amount of data to zero-copy over in one call.

Ciao
Stephan

**Comment by abgnwl** [comment]
Hi Stephan,
I got it. Thanks for your help!

**Comment by smuellerDD** [comment]
Am Donnerstag, 9. Juni 2022, 13:25:38 CEST schrieb Lizijue:

Hi Lizijue,

> Hi Stephan,
> I got it. Thanks for your help!

I apologize for the delay. The coding in ESDM took me longer than expected...

Ciao
Stephan
