### ISSUE TITLE
coreutils, etc. symlinks created in $PREFIX/libexec/libkcapi

### ISSUE THREAD

**Issue by caedmon-kitty** [smuellerDD/libkcapi#173]
The symlinks for the coreutils, fipscheck, fipshmac and hmaccalc are created in $PREFIX/libexec/libkcapi.  Is this expected?  I would have though they would be in $PREFIX/bin.

**Comment by smuellerDD** [comment]
Am Donnerstag, 7. September 2023, 20:49:53 CEST schrieb caedmon-kitty:

Hi caedmon,

> The symlinks for the coreutils, fipscheck, fipshmac and hmaccalc are created
> in $PREFIX/libexec/libkcapi.  Is this expected?  I would have though they
> would be in $PREFIX/bin.

This was added with patch 151583f205d8fe62b92df58671c7b9cf57fd7b65 suggested 
by a developer from a distro.

Ciao
Stephan

**Comment by caedmon-kitty** [comment]
I am not sure this is a good thing to do.  libexec should be for executable files invoked by other executables - gcc for example finds its  phases in libexec.

I am not aware of anyone who has libexec nor its subdirectories in their PATH.  I think at least coreutil and hmaccalc should be in $PREFIX/bin since $prefix/bin is usually in one's PATH.  Unless I am missing something and the those are not meant to be executed directly.

At least installing them in libexec should be an option, not the default.

**Comment by xnox** [comment]
> The symlinks for the coreutils, fipscheck, fipshmac and hmaccalc are created in $PREFIX/libexec/libkcapi. Is this expected? I would have though they would be in $PREFIX/bin.

There have been multiple changes in the master branch of libkcapi. Previously the project native multi-call kcapi-dgst was not installed at all. Now kcapi-dgst is installed in /usr/bin and it is the preferred binary to use to access all possible imitations of any other tool.

Separately, previously in violation of all guidelines of all Linux distributions hardlinks were used to create immitations of all the tools that kcapi-dgst is capable of replacing. Also the paths that libkcapi would install them into would conflict with all the alternative implementations making it impossible to have coinstalled sha1sum from both coreutils & libkcapi at the same time, to benchmark one against the other, or to compare the results of one another.

The default upstream installation now provides all symlinks to all tools in the non-conflicting libkcapi project specific location $PREFIX/libexec/libkcapi such that by default one can coinstall libkcapi toolings with all other projects providing the original or alternative implementation of all the tools.

Distributions that package libkcapi already ignored the hardlinks and recreated only subset of them, or chose not to enable libkcapi-dgst at all, reducing the available functionality of libkcapi that is otherwise possible to access.

Distributions that are upgrading to the master git snapshot of this project, can continue to package symlinks in a way that suits them, and can create those that conflict with coreutils / fipscheck / and so on tools. Or use any appropriate mechanisms to manage those (i.e. deb based distributions maintainers or end users can for example use dpkg-divert functionality to provide additional packages that without conflicts takeover the binaries available from coreutils / fipscheck / etc).

The goal here is to reduce conflicts, and promote kcapi-dgst to be available by default in all distributions and directly usable by all ensuring they are leveraging the kernel implementation. Distributions that package libkcapi should try to make kcapi-dgst to be always available, and for example make kcapi-defaultutils subpackage that conflicts/replaces/diverts and installs all the possible kcapi-dgst tools in /usr/bin for those that desire to only use libkcapi implementation of these.

I really want people to have kcapi-dgst available by default, and users to use it directly if possible. Instead of relying on compatiblity shims of mimicking other tools.

Separately, if it is desired, I can implement a configure or make install option to generate symlinks for all tools which would conflict with coreutils / fipscheck / and so on, if that would help non-distribution users of libkcapi to get back previous behaviour of conflicting with essential tools that are normally preinstalled and required in all linux distributions.

Does this adequately explain the new installation features and benefits in the current master?
Are you a distribution package maintainer (if yes, which), or are you a direct end user?
Would a configure option to force installing symlinks into conflicting binary paths help you?
Are you able to switch your usage to kcapi-dgst tool directly that alone can produce any and all desired options of all tools previously shipped - and more!?
