### ISSUE TITLE
kcapi_pbkdf with iteration count = 0 zeroes output buffer

### ISSUE THREAD

**Issue by guidovranken** [smuellerDD/libkcapi#93]
It should return an error, because only iteration counts > 0 are valid: https://tools.ietf.org/html/rfc2898#section-5.2

**Comment by smuellerDD** [comment]
Fixed

**Comment by guidovranken** [comment]
Maybe you meant to close https://github.com/smuellerDD/libkcapi/issues/92 (assuming it is related to https://github.com/smuellerDD/libkcapi/pull/91) ?

**Comment by smuellerDD** [comment]
Am Dienstag, 5. Mai 2020, 21:45:52 CEST schrieb Guido Vranken:

Hi Guido,

> Maybe you meant to close https://github.com/smuellerDD/libkcapi/issues/92
> (assuming it is related to https://github.com/smuellerDD/libkcapi/pull/91)
> ?

I meant to close your report. I have applied the fix, but did not push it. 
Note, I am not using the github services for managing patches since I am going 
to sign every patch. And rest assured, I am not uploading my private key to 
github :-)

Thus, give me a couple of minutes and then you will see the change.

Ciao
Stephan

**Comment by guidovranken** [comment]
Ok, sure, thanks.
